services:
  event_db:
    image: postgres:13
    environment:
      - POSTGRES_USER=event_user
      - POSTGRES_PASSWORD=event_pass
      - POSTGRES_DB=event_db
    volumes:
      - event_db_data:/var/lib/postgresql/data
      - ./db_init/event_db:/docker-entrypoint-initdb.d
    networks:
      - eventhive-network
  user_db:
    image: postgres:13
    environment:
      - POSTGRES_USER=user_user
      - POSTGRES_PASSWORD=user_pass
      - POSTGRES_DB=user_db
    volumes:
      - user_db_data:/var/lib/postgresql/data
    networks:
      - eventhive-network
  event_service:
    build: ./event_service
    ports:
      - "5002:5002"
    environment:
      - DATABASE_USER=event_user
      - DATABASE_PASSWORD=event_pass
      - DATABASE_HOST=event_db   
      - DATABASE_PORT=5432
      - DATABASE_NAME=event_db 
    depends_on:
      - event_db
    networks:
      - eventhive-network
  user_service:
    build: ./user_service
    ports:
      - "5001:5001"
    environment:
      - EVENT_SERVICE_URL=http://event_service:5002
    depends_on:
      - event_service
    networks:
      - eventhive-network
volumes:
  event_db_data:
  user_db_data:
networks:
  eventhive-network:
    driver: bridge